### PR TITLE
Renamed the module imports

### PR DESCRIPTION
**Pull request by theintegrative**
Now it is able to start up

### CODE REVIEW

**Comment by JanCBrammer** [comment]
Thanks for the PR @theintegrative. 

For my understanding: How are you running OpenHRV / in what situation do the absolute imports give you trouble?

**Comment by theintegrative** [comment]
On my Ubuntu Linux host I started the app using these commands:
``` 
theintegrative@home:~/github/other-repos/OpenHRV/openhrv$ python3 app.py 
theintegrative@home:~/github/other-repos/OpenHRV$ python3 openhrv/app.py 
``` 
From both I get this feedback:
``` 
Traceback (most recent call last):
  File "/home/theintegrative/github/other-repos/OpenHRV/openhrv/app.py", line 3, in <module>
    from openhrv.view import View
ModuleNotFoundError: No module named 'openhrv'
```

**Comment by theintegrative** [comment]
Thanks! All the methods you mention above are working for me. I do love the app:)

**Comment by JanCBrammer** [comment]
Thanks for the kind feedback :blush: Closing with 2b0d3ecb72d7be3cf594b1533772b3f0f6ad5715.

**Pull request closed without merging**
